AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Guardfile'
    - 'lib/tasks/**/*'
    - 'bin/setup'
    - 'bin/spring'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Rakefile'

Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false
